BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS entries ( PrecursorMz double not null, PrecursorCharge int not null, PeptideModSeq string not null, PeptideSeq string not null, Copies int not null, RTInSeconds double not null, Score double not null, MassEncodedLength int not null, MassArray blob not null, IntensityEncodedLength int not null, IntensityArray blob not null, CorrelationEncodedLength int, CorrelationArray blob, QuantifiedIonsArray blob, RTInSecondsStart double, RTInSecondsStop double, IonMobility double, MedianChromatogramEncodedLength int, MedianChromatogramArray blob, SourceFile string not null );
CREATE TABLE IF NOT EXISTS fragmentquants ( PrecursorCharge int not null, PeptideModSeq string not null, PeptideSeq string not null, SourceFile string not null, IonType string not null, IonIndex int not null, FragmentMass double not null, Correlation double not null, Background double not null, DeltaMassPPM double not null, Intensity double not null );
CREATE TABLE IF NOT EXISTS metadata ( Key string not null, Value string not null );
CREATE TABLE IF NOT EXISTS peptidelocalizations ( PrecursorCharge int not null, PeptideModSeq string not null, PeptideSeq string not null, SourceFile string not null, LocalizationPeptideModSeq string, LocalizationScore double, LocalizationFDR double, LocalizationIons string, NumberOfMods int, NumberOfModifiableResidues int, IsSiteSpecific boolean, IsLocalized boolean, RTInSecondsCenter double, LocalizedIntensity double, TotalIntensity double );
CREATE TABLE IF NOT EXISTS peptidequants ( PrecursorCharge int not null, PeptideModSeq string not null, PeptideSeq string not null, SourceFile string not null, RTInSecondsCenter double not null, RTInSecondsStart double not null, RTInSecondsStop double not null, TotalIntensity double not null, NumberOfQuantIons int not null, QuantIonMassLength int not null, QuantIonMassArray blob not null, QuantIonIntensityLength int, QuantIonIntensityArray blob, QuantIonCorrelationLength int, QuantIonCorrelationArray blob, BestFragmentCorrelation double not null, BestFragmentDeltaMassPPM double not null, MedianChromatogramEncodedLength int not null, MedianChromatogramArray blob not null, MedianChromatogramRTEncodedLength int, MedianChromatogramRTArray blob, IdentifiedTICRatio double not null );
CREATE TABLE IF NOT EXISTS peptidescores ( PrecursorCharge int not null, PeptideModSeq string not null, PeptideSeq string not null, SourceFile string not null, QValue double not null, PosteriorErrorProbability double not null, IsDecoy boolean not null );
CREATE TABLE IF NOT EXISTS peptidetoprotein (PeptideSeq string not null,isDecoy boolean,ProteinAccession string not null);
CREATE TABLE IF NOT EXISTS proteinscores ( ProteinGroup int not null, ProteinAccession string not null, SourceFile string not null, QValue double not null, MinimumPeptidePEP double not null, IsDecoy boolean not null );
CREATE TABLE IF NOT EXISTS retentiontimes (SourceFile string not null, Library float not null, Actual float not null, Predicted float not null, Delta float not null, Probability float not null, Decoy boolean, PeptideModSeq string);
CREATE INDEX 'IonMobility_Entries_index' on 'entries' ('IonMobility' ASC);
CREATE INDEX 'Key_Metadata_index' on 'metadata' ('Key' ASC);
CREATE INDEX 'PeptideModSeq_PrecursorCharge_SourceFile_Entries_index' on 'entries' ('PeptideModSeq' ASC, 'PrecursorCharge' ASC, 'SourceFile' ASC);
CREATE INDEX 'PeptideModSeq_PrecursorCharge_SourceFile_Fragments_index' on 'fragmentquants' ('PeptideModSeq' ASC, 'PrecursorCharge' ASC, 'SourceFile' ASC);
CREATE INDEX 'PeptideModSeq_PrecursorCharge_SourceFile_Localizations_index' on 'peptidelocalizations' ('PeptideModSeq' ASC, 'PrecursorCharge' ASC, 'SourceFile' ASC);
CREATE INDEX 'PeptideModSeq_PrecursorCharge_SourceFile_Peptides_index' on 'peptidequants' ('PeptideModSeq' ASC, 'PrecursorCharge' ASC, 'SourceFile' ASC);
CREATE INDEX 'PeptideModSeq_PrecursorCharge_SourceFile_Scores_index' on 'peptidescores' ('PeptideModSeq' ASC, 'PrecursorCharge' ASC, 'SourceFile' ASC);
CREATE INDEX 'PeptideSeq_Entries_index' on 'entries' ('PeptideSeq' ASC);
CREATE INDEX 'PeptideSeq_Fragments_index' on 'fragmentquants' ('PeptideSeq' ASC);
CREATE INDEX 'PeptideSeq_Localizations_index' on 'peptidelocalizations' ('PeptideSeq' ASC);
CREATE INDEX 'PeptideSeq_PeptideToProtein_index' on 'peptidetoprotein' ('PeptideSeq' ASC);
CREATE INDEX 'PeptideSeq_Peptides_index' on 'peptidequants' ('PeptideSeq' ASC);
CREATE INDEX 'PeptideSeq_Scores_index' on 'peptidescores' ('PeptideSeq' ASC);
CREATE INDEX 'PrecursorMz_Entries_index' on 'entries' ('PrecursorMz' ASC);
CREATE INDEX 'ProteinAccession_PeptideToProtein_index' on 'peptidetoprotein' ('ProteinAccession' ASC);
CREATE INDEX 'ProteinAccession_ProteinScores_index' on 'proteinscores' ('ProteinAccession' ASC);
CREATE INDEX 'ProteinGroup_ProteinScores_index' on 'proteinscores' ('ProteinGroup' ASC);
COMMIT;
